### ISSUE TITLE
Support is greater than 1

### ISSUE THREAD

**Issue by CicoZhang** [adoku14/Eclat-Python-Implementation#1]
Just a minor question.
Can `support` be greater than 1? (The given example uses `support` as 3))

From Wikipedia, it says:
![image](https://user-images.githubusercontent.com/11710225/46354256-7c557180-c65e-11e8-8931-a84b854a1d86.png)

Thanks.

**Comment by adoku14** [comment]
The support also called the frequency can be defined in 2 different ways. One way is what you saw in wikipedia which ratio of frequency and the total number of transactions ( being in a range from 0-1) or the number of occurences. In my implementation i print only the number of occurences for the specific frequent itemset but you can modify it by diving by the number of total transaction to have a range between 0 and 1. I hope i was clear to you.

**Comment by CicoZhang** [comment]
Thank you for the quick explanation, now it is totally clear to me.
